gems:
  - jekyll-redirect-from

url: https://www.sonetin.com

tagline:
  en: "Your Private Communities"
  fr: "Vos Communautés Privées"
description:
  en: "Your Private Social Network. A private free & unlimited space, with your friends, association, company."
  fr: "Votre Réseau Social Privé. Un espace privé, gratuit et illimité, avec vos amis, votre association, votre entreprise."
keywords:
  en: "free,social,network,friends,coworkers"
  fr: "reseau,social,gratuit,amis,collegues,network,free"
