markdown: rdiscount
pygments: true
description:
  en: Your Private Social Network. A private free & unlimited space, with your friends, association, company.
  fr: Votre Réseau Social Privé. Un espace privé, gratuit et illimité, avec vos amis, votre association, votre entreprise.
navigation:
  en:
    - text: Features
      url: '../en/#features'
#    - text: Home
#      url: ../en/
#    - text: Solution
#      url: solution.html
#    - text: Contact
#      url: contact.html
  fr:
    - text: Fonctionnalités
      url: '../fr/#features'
#    - text: Accueil
#      url: ../fr/
#    - text: Solution
#      url: solution.html
#    - text: Nous contacter
#      url: contact.html
footer:
  en:
    - "company:":
      - text: About us
        url: about.html
      - text: Contact us
        url: contact.html
      - text: Terms
        url: legal.html
    - "community:":
      - text: Blog
        url: http://blog.sonetin.com
      - text: Twitter
        url: http://twitter.com/sonet_in
    - "language:":
      - text: English
        url: ../en/
      - text: Français
        url: ../fr/
  fr:
    - "entreprise :":
      - text: A propos
        url: a-propos.html
      - text: Nous contacter
        url: contact.html
      - text: Légal
        url: legal.html
    - "communauté :":
      - text: Blog
        url: http://blog.sonetin.com
      - text: Twitter
        url: http://twitter.com/sonet_in
    - "langue :":
      - text: English
        url: ../en/
      - text: Français
        url: ../fr/
analytics:
  google:
    tracking_id: UA-39068713-1
